name: Run LBANK Bot (Self-hosted, 15h daily)

on:
  workflow_dispatch:
  schedule:
    # 1 vez al día a las 12:00 UTC (ajusta a gusto)
    - cron: "0 12 * * *"

concurrency:
  group: lbank-bot-selfhosted
  cancel-in-progress: false

jobs:
  run:
    # Etiquetas que pondremos al runner (ver script de instalación)
    runs-on: [self-hosted, windows, bot]
    # Límite del job: 16h de margen (self-hosted permite hasta 5 días)
    timeout-minutes: 960

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build .env from secrets
        run: |
          @"
          MODE=demo_realtime_auto
          EXCHANGE=lbank
          API_KEY=${{ secrets.LBANK_API_KEY }}
          API_SECRET=${{ secrets.LBANK_API_SECRET }}

          TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_ALLOWED_IDS=${{ secrets.TELEGRAM_ALLOWED_IDS }}

          SYMBOLS=BTC/USDT,ETH/USDT,BNB/USDT,SOL/USDT,XRP/USDT,ADA/USDT,DOGE/USDT,TON/USDT,LINK/USDT,AVAX/USDT,TRX/USDT,LTC/USDT,NEAR/USDT

          TIMEFRAME_LTF=5m
          TIMEFRAME_HTF=1h

          RISK_AGRESIVO=0.03
          RISK_MODERADO=0.02
          RISK_CONSERVADOR=0.01

          DEMO_MAX_TRADE_USDT=100
          DEMO_MAX_POSITIONS=5
          MIN_NOTIONAL_USDT=10

          FEE_TAKER=0.001
          SPREAD_BPS=0.0003

          MIN_24H_VOLUME_USDT=10000000
          ADX_MIN=20
          ATR_PCTL_MIN=35
          RSI_MIN=45
          RSI_MAX=60
          MAX_EMA_DIST_ATR=0.8

          EMA_FAST=35
          EMA_SLOW=50
          ATR_PERIOD=14

          ATR_K_AGRESIVO=2.2
          ATR_K_MODERADO=2.6
          ATR_K_CONSERVADOR=3.0
          TP_R_AGRESIVO=1.8
          TP_R_MODERADO=2.0
          TP_R_CONSERVADOR=2.2

          ADX_PERIOD=14
          ATR_PCTL_WINDOW=200
          ADX_HIGH=25
          ADX_LOW=18
          ATR_PCTL_HIGH=50
          ATR_PCTL_LOW=30
          PROFILE_LOCK_MIN=20

          CONFIRM_ON_CLOSE=1
          ENTRY_COOLDOWN_MIN=10
          SYMBOL_LOCK_MIN=15
          ALLOW_SAME_SYMBOL=0

          # ⏱️ Corre 15 horas (54000s). El job tiene margen con timeout-minutes.
          RUNTIME_SEC=54000
          SLEEP_SEC=5
          TIMEOUT_MIN=30
          AUTO_SUMMARY_MIN=30

          CSV_PATH=operaciones.csv
          SUMMARY_MAX_OPS=100
          PAPER_START_BALANCE=1000
          "@ | Out-File -FilePath .env -Encoding utf8

      - name: Run bot (paper)
        run: python run_bot_realtime_auto.py

      - name: Upload CSV artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: operaciones-${{ github.run_id }}
          path: operaciones.csv
